### ISSUE TITLE
Roadmap for Next Year

### ISSUE THREAD

**Issue by mmcleod89** [UCL/hivpy#145]
- Look at transmission code + CD4 / viral load for people not on treatment 
- Testing diagnosis (depends on date of infection) 
- Assume 3 drugs: tenofovir (ten), 3tc, dol
- Only subset of resistance mutations are relevant to these drugs 
- Starting with ART & adherence, then resistance 
- ignore code with `pop_wide_tld=1`
- Prep later if we have time!

**Comment by andrew-phillips-1** [comment]
Hi @mmcleod89 and @pineapple-cat   

For when you return from holidays:

What would be the best way for us to comment on existing code ?  I tried to create a branch from development and was going to insert any questions or comments I had in that and then do a dummy pull request, but I'm sure there is a better way.  In any case, I failed to sync with pycharm so I clearly need some more help with doing that at some point. 

Also, I think it would be helpful if you show us how to run a basic version of the model as it stands.  Even if all this does is update people's sexual behaviour it will be very useful for us to start to see outputs.

Thanks

**Comment by pineapple-cat** [comment]
Unfortunately, I don't believe it's currently possible to comment on existing code that hasn't been changed. This really should be a feature though, it would be very helpful for our use case (and it would help other translators too).

In any case, you seem to have had the right idea and I can't think of a better workaround than this:
- Make a new branch (e.g. `hivpy-discussion`)
- Make a new PR (e.g. `HIVpy discussion`)
- Add various short remarks/questions to the Python code and push the changes
- Then add further/longer GitHub comments to your initial Python comments
    - Find the `Files changed` tab in your PR
    - Click on the blue `+` icon next to any displayed line to leave a comment on that line (or click and drag the `+` icon down to select multiple lines to comment on)

We can use this PR as a forum for questions, answers, clarifications, suggestions, and anything else you can think of.

**Comment by andrew-phillips-1** [comment]
ok thanks Emily

**Comment by mmcleod89** [comment]
Closing this roadmap issue as things have changed since our extension
