### ISSUE TITLE
Outputs for early epidemic tests 

### ISSUE THREAD

**Issue by mmcleod89** [UCL/hivpy#158]
Outputs for checking the behaviour of the simulation in the early epidemic (pre-treatment & testing)

See example outputs given by Jenny, but this will mostly focus on things like:
- Number of people in each age bracket
- Number of deaths
- Number of sexual partners w/demographics
- Number of people with HIV w/demographics
- Number of births

Won't include things like testing as we're focusing on the early era. 

- [x] Output module should write these outputs for each timestep into an output file. 
- [x] Also want to be able to make graphs. (May be post processing or automatic.) 
- [x] List desired outputs in config file. 
- [x] Python script for creating comparison plots of single runs with SAS data. (Extended by #171 to allow data aggregation and averages across multiple runs.)

**Comment by pineapple-cat** [comment]
Current list of outputs to include (from 21/11/23 meeting):

- [x] proportion of people aged 15-64 with a long-term partner (`p_ep`)
- [x] proportion of people aged 15-64 with at least one short-term partner (`p_newp_ge1`)
- [x] proportion of people aged 15-64 with at least five short-term partners (`p_newp_ge5`)
- [x] proportion of women giving birth
- [x] of women with HIV giving birth, proportion of children infected
- [x] proportion of circumcised men aged 15-49
- [x] proportion of female sex workers
- [x] proportion of female sex workers with HIV
- [x] proportion of people aged 15-49 with HIV (prevalence)
- [x] measure of new HIV cases in women and men aged 15-24 (incidence)
- [x] measure of new HIV cases in people aged 15-49 and 15-64 (incidence)
- [ ] of the infections in a given time-step, proportion of people that have been infected by a long-term partner (`p_inf_ep`) (relies on #162)
- [x] of the infections in a given time-step, proportion of people that have been infected by someone in the primary infection phase (`p_inf_primary`)
- [x] number of women and men aged 15+ and 20-59 dead (`n_death_2059_w`, `n_death_2059_m`)
- [x] number of people with CD4 counts <200, 200-500, and >500 (`n_cd4_lt200`)
- [x] number of people aged 15+ alive (`n_alive`)
- [x] number of people with HIV (`n_hiv`)
- [x] number of live births
- [x] number of births to infected women

Additional outputs for validation:

- [x] short-term partner gender balance (`log_gender_r_newp`)
- [x] short-term partner gender balance divided by age groups (`logm15r`, `logm25r`, `logm35r`, `logm45r`, `logm55r`, `logw15r`, `logw25r`, `logw35r`, `logw45r`, `logw55r`)
- [x] of the infections in a given time-step, proportion of people that have been infected by a short-term partner (`p_inf_newp`)

**Comment by mmcleod89** [comment]
As an example for the log gender balance variables, I think the calculation is as follows:
for `logm15r` this is for men with 15 <= age < 25
- The numerator is: sum of short term partners over all men in this age bracket
- The denominator is: looking at all sexually active women, add up the short term partners who are men 15-25. (For us this is made a bit more complicated by the fact that each short term partner is allowed to have their own age.)
- Take the log of this ratio

@UCL/hiv-modelling  does this calculation look right to you?

**Comment by andrew-phillips-1** [comment]
Hi Michael @mmcleod89  - Thanks - this looks right to me, yes.

**Comment by mmcleod89** [comment]
Considering #171 as a separate rather than sub-issue going forward
