### ISSUE TITLE
Review and Config of Simulation Output

### ISSUE THREAD

**Issue by pweschmidt** [UCL/hivpy#31]
Should it be removed from the SimulationConfig?

- which place in the Config file
- how should it be passed into the code 
- eliminate the track attributes

**Comment by NovusEdge** [comment]
Hi There!

I would like to take this issue if no one's assigned
Please let me know the specifics (if any).

**Comment by ageorgou** [comment]
- Remove tracked attributes completely in favour of `SimulationOutput`
- Restructure config file:
    - Switch to YAML
    - Move output directory setting out of simulation config; create an output section (with subsections for logging, simulation, ...?)
    - Pass simulation output path to `SimulationHandler` constructor
- Remove `run_simulation` (replace with calls to `SimulationHandler`)
- `SimulationOutput`: remove output path, only pass in as argument to `write_output`
