### ISSUE TITLE
Plan Python Intro

### ISSUE THREAD

**Issue by pweschmidt** [UCL/hivpy#32]
Most of the researchers are not familiar or lack experience in programming with Python.
In our next demo on 1 March we want to 
- give them a highlevel overview of what a Python program/script looks like

This ticket is to plan this activity/demo

**Comment by ageorgou** [comment]
Topics to cover:
- What does a file look like?
- How do we run it?
- Defining functions
- Basic types and arithmetic

**Comment by ageorgou** [comment]
Plan:

- Fork repository
- Open in PyCharm
- Basic syntax: assignment, arithmetic, print
- Running file
- Exercise: add print statement for e.g. x**2 (using Code With Me)
- Functions (example: death rate)
    - Describe exercise (eprate), solve if time
- If statements (example: probability of starting sex work)
     - Describe exercise (equation 9), solve if time
