### ISSUE TITLE
Detailed calculation of risk reduction factor (rred) at each time step

### ISSUE THREAD

**Issue by pweschmidt** [UCL/hivpy#36]

**Comment by mmcleod89** [comment]
Additional risk factors:
- [x] rred_balance (balance of sexual partners across sex/age groups)
- [x] rred_ep (long term partner) 
- [x] rred_a (age based risk reduction, updated)
- [x] rred_adc (AIDS defining condition)
- [x] rred_d (risk reduction following diagnosis)
- [x] rred_rc (general population)
- [x] rred_p (personal risk factor)
- [x] rred_adhav (adherence to ART)
- [x] newp_factor (new partner factor)

Some of these will have some placeholder functionality if there are non-trivial dependencies which are not implemented yet
