### ISSUE TITLE
Code documentation (doxygen style)

### ISSUE THREAD

**Issue by pweschmidt** [UCL/hivpy#40]
We should add code comments in our functions, classes, modules . 
To be decided: to what level of detail/granularity 
To be decided: style and framework

**Comment by ageorgou** [comment]
For a framework, my suggestion is [Sphinx](https://www.sphinx-doc.org/), which is used widely for Python projects and has lots of plugins for input and output formats.

In terms of style, I found a useful [overview](https://stackoverflow.com/a/24385103), though perhaps a bit outdated. I think numpydoc (used by Numpy and other libraries) or reStructuredText (the sphinx default) are the most popular ones.

Personally, I would want to have a docstring for at least:
- Each model module, (the class e.g. `DemographisModule`), describing its purpose and maybe the variables it is primarily concerned with/responsible for.
- Each module's constructor and the main methods it provides.
- The methods of `Population`
- The utility functions/methods we have, e.g. for starting simulations
- Each test method, describing what it's checking, and each test fixture

Not all of these would necessarily have the full format (arguments, returns, exceptions, ...) - for some it may be fine to only have a one-line or brief description if obvious. Methods that are intended to be private could be fine with nothing, although I would still prefer at least a one-line docstring. That said, I'm happy to go with more stringent requirements if people prefer.
