### ISSUE TITLE
determining maximum age

### ISSUE THREAD

**Issue by andrew-phillips-1** [UCL/hivpy#68]
Hi Michael and Anastasis

I started looking at the hivpy code.   It will take me a while to understand but it is great to see this shaping up.

One question I had so far was about the maximum age.  When the simulation is running we will have the non-HIV death rates increasing with age as they do so the maximum age will take care of itself.  e.g. in 85+ year old men the death rate is 0.4 per year.  So I wasn't sure why you needed to pre-specify the maximum age.

If I have other comments, how would you like me to make them ?

**Comment by ageorgou** [comment]
Hi Andrew, could you tell us where you saw the maximum age? I don't think we impose a limit at the moment, but instead apply the death rates according to the age. The very first version we wrote pre-selected a maximum age for simplicity, so perhaps there is some remnant of that left in by accident.

Any comments are very welcome! If you notice that something is (or might be) wrong, like in this case, opening an issue would be best. Same if you want to discuss how to handle an aspect of the model that may not be implemented yet. It's helpful to keep issues specific, so if you have more general questions/comments about the direction of "travel", perhaps it's better to first discuss in a call or email, and then open the corresponding issue(s) after that.

In general, however, do feel free to comment here. We can also take everyone through the repository (both the code and the issues) on one of the calls, or after we do our next demo at the end of August.

**Comment by andrew-phillips-1** [comment]
Hi Anastasis

OK good thanks.

For max-age, I was looking for example at line 119 on demographics.py.

**Comment by ageorgou** [comment]
Ah, okay. That part has to do with how we initialise the ages across the population. There, `max_age` is the maximum age that someone can be assigned at time 0. That's currently 65 (that's not straightforward to see, but it's specified in [lines 129-135](https://github.com/UCL/hivpy/blob/a3277c3dab18887fb7e160a38e36bb9d3ab79819/src/hivpy/demographics.py#L129-L135))
https://github.com/UCL/hivpy/blob/a3277c3dab18887fb7e160a38e36bb9d3ab79819/src/hivpy/demographics.py#L129-L135

We should probably make the meaning of the arguments clearer, though, which we already have in mind as part of improving the code documentation (#40).

**Comment by andrew-phillips-1** [comment]
I see thanks.   Yes we have an initial age limit of 65 but there is no good reason for that and we can include all ages if not too difficult to do.   There is also   line 33   self.age_max = 100  in simulation.py but I don't see any problem with limiting to being below such a high age.

**Comment by ageorgou** [comment]
That one (100) has to do with the outputs we record. So, at the moment, the highest age group for which we report prevalence of HIV is 90-100. That one should be easy to extend if needed.

Regarding having no limit in the initial assignment of ages, I see two issues:
- People over 65 are (I think?) ignored in many parts of the model, so starting at higher ages may effectively reduce the size of the population
- The statistical models we use for choosing the initial age do require an upper limit. This is definitely the case for the discrete one (which mimics the behaviour of the SAS model), and also I think for the continuous one that we've added. I'll leave @mmcleod89  to verify that, though, as he's the one who investigated and implemented it. I seem to remember that it gives strange behaviours outside the permitted age limits (e.g. -65 to 65).

That said, if you think this would be useful in the new version of the model, we can look at it, even if it's not as a matter of urgency.

**Comment by andrew-phillips-1** [comment]
Thanks.  In that case we shouldn't try to change the initial age distribution.  Age 65 is the limit below which people can have condomless sex so that was the reason for limiting the initial age.  It is fine to keep it as is.
