### ISSUE TITLE
Pregnancy

### ISSUE THREAD

**Issue by ageorgou** [UCL/hivpy#79]

**Comment by mmcleod89** [comment]
- Model pregnancy explicitly instead of retro-actively 
- Not implementing testing related functionality at the moment

**Comment by pineapple-cat** [comment]
Feature description from model details doc:

> ### Pregnancy and Parity
> 
> Pregnancy is modelled at the point of childbirth. In a given three-month period, a women has a pregnancy risk (i.e. modelled as childbirth) if she had one or more short- or long-term condomless partners 9 months previously. The baseline probability per condomless partner of a woman being pregnant in each three-month period is fixed throughout the simulation. This can be modified by a number of population-level and individual-level factors, described in Table S3. Pregnancy risk is calculated separately for each condomless partner. 95% of women are assumed to ever be able to become pregnant and each woman can have a maximum of 10 children. A woman can become pregnant 6 months after their previous birth.

> ### Parameters relating to pregnancy (from Table S3 & Table S27)
> 
> `prob_pregnancy_base` - Parameter determining base rate of pregnancy for women having condomless sex (to which there is an effect of age). May be affected by the value of `inc_cat`.
> `fold_preg` - A fertility variable that decreases with age.
> `fold_tr_newp` - Pregnancy risk from short-term condomless partner. If a woman had one or more short-term condomless partners 9 months previously, pregnancy risk is reduced (per partner) due to the assumed lower number of sex acts with a short-term compared to long-term partner. The factor `fold_tr_newp` is applied at population level and is the same reduction that also applies to HIV transmission risk from a short-term condomless partner.
> `rate_want_no_more_children` - It is assumed that women aged 25-54 years stop desiring more children at a rate of 0.5% per 3 months (termed `rate_want_no_more_children`), regardless of parity. These women have an 80% reduction in pregnancy risk at each time step.  
> `rate_birth_with_infected_child` - Parameter determining the risk of mother to child transmission (MTCT), for a given level of mother viral load.
> `oth_dol_adv_birth_e_risk_` - Risk of dolutegravir-induced adverse birth event, due to dolutegravir-induced weight gain.
