### ISSUE TITLE
Sex workers

### ISSUE THREAD

**Issue by ageorgou** [UCL/hivpy#80]

**Comment by mmcleod89** [comment]
Loveleen is best contact for sex worker code. 
Affects sex behaviour / risk factors. 
Testing?

**Comment by mmcleod89** [comment]
- [x] 5 behaviour groups with transition matrices
- [x] over 25s are limited to 30 STPs
- [x] sex worker program exists
- [x] Calculate STP for sex workers 
- [x] Start / stop sex work
- [ ] Assign appropriate behaviour groups for sex workers after start / stop 
- [ ] Sex worker initial group probabilities
- [x] Sex workers transition to category 1 when ending sex work 
- [x] Prob that sex worker program exists is 20% (i.e. 20% of simulations have SW Programs) (sw_program)
- [x] Stength of sex worker program also sampled at the beginning of sim. 
- [x] sw_program_visit determines whether sex worker visits program
- [x] life_sex_risk code?
- [x] initial sex worker status

Some factors will be covered later like sex worker engagement with PrEP and ART
