### ISSUE TITLE
Circumcision

### ISSUE THREAD

**Issue by ageorgou** [UCL/hivpy#81]

**Comment by pineapple-cat** [comment]
Feature description from model details doc:

> ### Male Circumcision
> Amongst those testing HIV negative, the probability of VMMC is influenced by the underlying VMMC rates (see Table S27 for values from which we sample), age and calendar year.  The range of probabilities of VMMC according to age and calendar year reflects the range of VMMC prevalence across the region.   VMMC is assumed to lead to a 60% lower risk of HIV acquisition from a given partner with HIV (14-16).

> ### Parameters relating to male circumcision (from Table S27)
> `circ_inc_rate` - Determines the rate with which male circumcision increases over time.
> `rel_incr_circ_post_2013` - Relative increase in VMMC after 2013.
> `circ_inc_15_19`, `circ_red_20_30`, `circ_red_30_50` - Relative increases in age groups.
> `prob_birth_circ` - Probability of circumcision at birth.
